name: Latest YouTube Videos
on:
  schedule:
    # Runs every 24 hour
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNGrKRkUt5YgFGMoZ3ulYKg"
      - name: Update blog too
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.souravlayek.com/rss"
